/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://e3eytyv2bzgttggkz5ch4ydtpa.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-as37dbb775h55ctaw5k3j5mysi",
    "aws_cognito_identity_pool_id": "us-east-1:0b1ccbf7-ad62-458b-80ca-9e9f00420c75",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_rKyUtqtpG",
    "aws_user_pools_web_client_id": "707l6alba8hu1uancok5p9aj6q",
    "oauth": {
        "domain": "fftcgonline-dev.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "https://localhost:8100/,https://fftcg.online/",
        "redirectSignOut": "https://localhost:8100/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_user_files_s3_bucket": "fftcg-static222040-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
